apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 4
  strategy:
    type: rollingUpdate
      maxUnavailable: 50%
      maxSurge: 0
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: blastomussa/flaskappv2
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        readinessProde:
          httpGet:
            path: /api/v1
            port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - port: 5000
